In [1]:
import pandas as pd
import numpy as np
new_merged_df = pd.read_csv('clean_data/new_merged_data.csv')

In [2]:
#shinus columns
iteration1df = new_merged_df.copy()
iteration1df = iteration1df.drop(columns=['SK_ID_CURR'], axis = 1)
iteration1df = iteration1df.drop(columns=['CODE_GENDER'])
iteration1df = iteration1df.drop(columns=['FLAG_OWN_REALTY'])

In [3]:
#jewels columns
iteration1df = iteration1df.drop(columns=['APARTMENTS_AVG'])
iteration1df = iteration1df.drop(columns=['BASEMENTAREA_AVG'])
iteration1df = iteration1df.drop(columns=['YEARS_BEGINEXPLUATATION_AVG'])
iteration1df = iteration1df.drop(columns=['YEARS_BUILD_AVG'])
iteration1df = iteration1df.drop(columns=['COMMONAREA_AVG'])
iteration1df = iteration1df.drop(columns=['ELEVATORS_AVG'])
iteration1df = iteration1df.drop(columns=['ENTRANCES_AVG'])
iteration1df = iteration1df.drop(columns=['FLOORSMAX_AVG'])
iteration1df = iteration1df.drop(columns=['FLOORSMIN_AVG'])
iteration1df = iteration1df.drop(columns=['LANDAREA_AVG'])

In [4]:
#roopas columns
iteration1df = iteration1df.drop(columns=['LIVINGAPARTMENTS_AVG'])
iteration1df = iteration1df.drop(columns=['LIVINGAREA_AVG'])
iteration1df = iteration1df.drop(columns=['NONLIVINGAPARTMENTS_AVG'])
iteration1df = iteration1df.drop(columns=['NONLIVINGAREA_AVG'])
iteration1df = iteration1df.drop(columns=['APARTMENTS_MODE'])
iteration1df = iteration1df.drop(columns=['BASEMENTAREA_MODE'])
iteration1df = iteration1df.drop(columns=['YEARS_BEGINEXPLUATATION_MODE'])
iteration1df = iteration1df.drop(columns=['YEARS_BUILD_MODE'])
iteration1df = iteration1df.drop(columns=['COMMONAREA_MODE'])
iteration1df = iteration1df.drop(columns=['ELEVATORS_MODE'])
iteration1df = iteration1df.drop(columns=['ENTRANCES_MODE'])
iteration1df = iteration1df.drop(columns=['FLOORSMAX_MODE'])
iteration1df = iteration1df.drop(columns=['FLOORSMIN_MODE'])
iteration1df = iteration1df.drop(columns=['LANDAREA_MODE'])
iteration1df = iteration1df.drop(columns=['LIVINGAPARTMENTS_MODE'])
iteration1df = iteration1df.drop(columns=['LIVINGAREA_MODE'])
iteration1df = iteration1df.drop(columns=['NONLIVINGAPARTMENTS_MODE'])
iteration1df = iteration1df.drop(columns=['NONLIVINGAREA_MODE'])
iteration1df = iteration1df.drop(columns=['APARTMENTS_MEDI'])
iteration1df = iteration1df.drop(columns=['BASEMENTAREA_MEDI'])
iteration1df = iteration1df.drop(columns=['YEARS_BEGINEXPLUATATION_MEDI'])
iteration1df = iteration1df.drop(columns=['YEARS_BUILD_MEDI'])
iteration1df = iteration1df.drop(columns=['COMMONAREA_MEDI'])
iteration1df = iteration1df.drop(columns=['ELEVATORS_MEDI'])
iteration1df = iteration1df.drop(columns=['ENTRANCES_MEDI'])
iteration1df = iteration1df.drop(columns=['FLOORSMAX_MEDI'])
iteration1df = iteration1df.drop(columns=['FLOORSMIN_MEDI'])

In [5]:
#anshikas columns
iteration1df = iteration1df.drop(columns=[
    'NONLIVINGAPARTMENTS_MEDI',
    'FONDKAPREMONT_MODE',
    'LIVINGAPARTMENTS_MEDI',
    'LANDAREA_MEDI',
    'NONLIVINGAREA_MEDI',
    'WALLSMATERIAL_MODE',
    'LIVINGAREA_MEDI',
    'HOUSETYPE_MODE'
])

In [6]:
# Compute correlations and ignore categorical variables first and delete all the low value numerical variables 
corr = iteration1df.corr(method='pearson', numeric_only=True)

# Get correlation of all numeric features with TARGET
target_corr = corr['TARGET']

# Filter features with low correlation (-0.1 < corr < 0.3)
low_corr_features = target_corr[(target_corr >= -0.05) & (target_corr <= 0.05)].index.tolist()

print("Low correlation featureas with TARGET:")
print(low_corr_features)

Low correlation featureas with TARGET:
['CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'OWN_CAR_AGE', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'LIVE_CITY_NOT_WORK_CITY', 'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [7]:
iteration1df = iteration1df.drop(columns=['CNT_CHILDREN'])
iteration1df = iteration1df.drop(columns=['AMT_INCOME_TOTAL'])
iteration1df = iteration1df.drop(columns=['AMT_CREDIT'])
iteration1df = iteration1df.drop(columns=['AMT_ANNUITY'])
iteration1df = iteration1df.drop(columns=['AMT_GOODS_PRICE'])
iteration1df = iteration1df.drop(columns=['REGION_POPULATION_RELATIVE'])
iteration1df = iteration1df.drop(columns=['DAYS_EMPLOYED'])
iteration1df = iteration1df.drop(columns=['DAYS_REGISTRATION'])
iteration1df = iteration1df.drop(columns=['OWN_CAR_AGE'])
iteration1df = iteration1df.drop(columns=['CNT_FAM_MEMBERS'])
iteration1df = iteration1df.drop(columns=['HOUR_APPR_PROCESS_START'])
iteration1df = iteration1df.drop(columns=['TOTALAREA_MODE'])
iteration1df = iteration1df.drop(columns=['OBS_30_CNT_SOCIAL_CIRCLE'])
iteration1df = iteration1df.drop(columns=['DEF_30_CNT_SOCIAL_CIRCLE'])
iteration1df = iteration1df.drop(columns=['OBS_60_CNT_SOCIAL_CIRCLE'])
iteration1df = iteration1df.drop(columns=['DEF_60_CNT_SOCIAL_CIRCLE'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_HOUR'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_DAY'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_WEEK'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_MON'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_QRT'])
iteration1df = iteration1df.drop(columns=['AMT_REQ_CREDIT_BUREAU_YEAR'])

In [8]:
# check the actual correlation of the categorical variables
from scipy.stats import chi2_contingency
results = {}
categorical_vars = [
    'NAME_CONTRACT_TYPE',
    'FLAG_OWN_CAR',
    'NAME_TYPE_SUITE',
    'NAME_INCOME_TYPE',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'FLAG_MOBIL',
    'FLAG_EMP_PHONE',
    'FLAG_WORK_PHONE',
    'FLAG_CONT_MOBILE',
    'FLAG_PHONE',
    'FLAG_EMAIL',
    'OCCUPATION_TYPE',
    'REGION_RATING_CLIENT',
    'REGION_RATING_CLIENT_W_CITY',
    'WEEKDAY_APPR_PROCESS_START',
    'REG_REGION_NOT_LIVE_REGION',
    'REG_REGION_NOT_WORK_REGION',
    'LIVE_REGION_NOT_WORK_REGION',
    'REG_CITY_NOT_LIVE_CITY',
    'REG_CITY_NOT_WORK_CITY',
    'LIVE_CITY_NOT_WORK_CITY',
    'ORGANIZATION_TYPE',
    'EMERGENCYSTATE_MODE',
    'FLAG_DOCUMENT_2',
    'FLAG_DOCUMENT_3',
    'FLAG_DOCUMENT_4',
    'FLAG_DOCUMENT_5',
    'FLAG_DOCUMENT_6',
    'FLAG_DOCUMENT_7',
    'FLAG_DOCUMENT_8',
    'FLAG_DOCUMENT_9',
    'FLAG_DOCUMENT_10',
    'FLAG_DOCUMENT_11',
    'FLAG_DOCUMENT_12',
    'FLAG_DOCUMENT_13',
    'FLAG_DOCUMENT_14',
    'FLAG_DOCUMENT_15',
    'FLAG_DOCUMENT_16',
    'FLAG_DOCUMENT_17',
    'FLAG_DOCUMENT_18',
    'FLAG_DOCUMENT_19',
    'FLAG_DOCUMENT_20',
    'FLAG_DOCUMENT_21'
]

bureau_features = [
    'MAX_AMT_CREDIT_SUM_OVERDUE',
    'DEBT_RATIO',
    'AVERAGE_CREDIT_DAY_OVERDUE',
    'TOTAL_CREDIT_LIMIT',
    'SUM_CNT_CREDIT_PROLONG',
    'CREDIT_TYPE_Another type of loan',
    'CREDIT_TYPE_Car loan',
    'CREDIT_TYPE_Cash loan (non-earmarked)',
    'CREDIT_TYPE_Consumer credit',
    'CREDIT_TYPE_Credit card',
    'CREDIT_TYPE_Interbank credit',
    'CREDIT_TYPE_Loan for business development',
    'CREDIT_TYPE_Loan for purchase of shares (margin lending)',
    'CREDIT_TYPE_Loan for the purchase of equipment',
    'CREDIT_TYPE_Loan for working capital replenishment',
    'CREDIT_TYPE_Microloan',
    'CREDIT_TYPE_Mobile operator loan',
    'CREDIT_TYPE_Mortgage',
    'CREDIT_TYPE_Real estate loan',
    'CREDIT_TYPE_Unknown type of loan',
    'MAX_RECENCY_CLOSED_LOAN',
    'AVG_LOAN_DURATION_ACTUAL',
    'MAX_OVERDUE_AMOUNT',
    'COUNT_OVERDUE_LOANS',
    'TOTAL_ACTIVE',
    'TOTAL_CLOSED',
    'TOTAL_SOLD',
    'TOTAL_BAD_DEBT',
    'COUNT_LOCAL_CURRENCY_LOANS',
    'COUNT_FOREIGN_CURRENCY_LOANS',
    'DAYS_CREDIT_RECENT',
    'DAYS_CREDIT_OLDEST',
    'RECENT_LOAN_COUNT',
    'AVERAGE_DAYS_OVERDUE',
    'AVERAGE_DAYS_CREDIT_UPDATE',
    'TOTAL_ANNUITY'
]

categorical_vars = categorical_vars + bureau_features

for var in categorical_vars:
    table = pd.crosstab(iteration1df[var], iteration1df['TARGET'])
    chi2, p, dof, expected = chi2_contingency(table)
    results[var] = float(p)

In [9]:
useless = []
for variable in results:
    if(results[variable] > 0.5):
        useless.append(variable)

useless

['FLAG_MOBIL',
 'FLAG_EMAIL',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'EMERGENCYSTATE_MODE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'MAX_RECENCY_CLOSED_LOAN',
 'AVG_LOAN_DURATION_ACTUAL',
 'DAYS_CREDIT_RECENT',
 'DAYS_CREDIT_OLDEST',
 'AVERAGE_DAYS_OVERDUE',
 'AVERAGE_DAYS_CREDIT_UPDATE']

In [10]:
#drop useless columns
iteration1df = iteration1df.drop(columns=['FLAG_MOBIL',
 'FLAG_EMAIL',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'EMERGENCYSTATE_MODE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'MAX_RECENCY_CLOSED_LOAN',
 'AVG_LOAN_DURATION_ACTUAL',
 'DAYS_CREDIT_RECENT',
 'DAYS_CREDIT_OLDEST',
 'AVERAGE_DAYS_OVERDUE',
 'AVERAGE_DAYS_CREDIT_UPDATE'])

In [11]:
remaining_categorical_vars = [
    'NAME_CONTRACT_TYPE',
    'FLAG_OWN_CAR',
    'NAME_TYPE_SUITE',
    'NAME_INCOME_TYPE',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'FLAG_EMP_PHONE',
    'FLAG_WORK_PHONE',
    'FLAG_CONT_MOBILE',
    'FLAG_PHONE',
    'OCCUPATION_TYPE',
    'REGION_RATING_CLIENT',
    'REGION_RATING_CLIENT_W_CITY',
    'WEEKDAY_APPR_PROCESS_START',
    'REG_REGION_NOT_LIVE_REGION',
    'REG_CITY_NOT_LIVE_CITY',
    'REG_CITY_NOT_WORK_CITY',
    'LIVE_CITY_NOT_WORK_CITY',
    'ORGANIZATION_TYPE',
    'FLAG_DOCUMENT_3',
    'FLAG_DOCUMENT_5',
    'FLAG_DOCUMENT_6',
    'FLAG_DOCUMENT_8',
    'FLAG_DOCUMENT_9',
    'FLAG_DOCUMENT_11',
    'FLAG_DOCUMENT_13',
    'FLAG_DOCUMENT_14',
    'FLAG_DOCUMENT_15',
    'FLAG_DOCUMENT_16',
    'FLAG_DOCUMENT_18',
    'FLAG_DOCUMENT_21'
]

In [12]:
# # all numeric columns not including those that are in bureau data with no history
# numeric_columns = []
# CNT_CHILDREN
# AMT_INCOME_TOTAL
# AMT_CREDIT
# AMT_ANNUITY
# AMT_GOODS_PRICE
# REGION_POPULATION_RELATIVE
# DAYS_BIRTH
# DAYS_EMPLOYED
# DAYS_REGISTRATION
# DAYS_ID_PUBLISH
# OWN_CAR_AGE
# CNT_FAM_MEMBERS
# HOUR_APPR_PROCESS_START
# EXT_SOURCE_1
# APARTMENTS_AVG
# BASEMENTAREA_AVG
# YEARS_BEGINEXPLUATATION_AVG
# YEARS_BUILD_AVG
# COMMONAREA_AVG
# ELEVATORS_AVG
# ENTRANCES_AVG
# FLOORSMAX_AVG
# FLOORSMIN_AVG
# LANDAREA_AVG
# LIVINGAPARTMENTS_AVG
# LIVINGAREA_AVG
# NONLIVINGAPARTMENTS_AVG
# NONLIVINGAREA_AVG
# APARTMENTS_MODE
# BASEMENTAREA_MODE
# YEARS_BEGINEXPLUATATION_MODE
# YEARS_BUILD_MODE
# COMMONAREA_MODE
# ELEVATORS_MODE
# ENTRANCES_MODE
# FLOORSMAX_MODE
# FLOORSMIN_MODE
# LANDAREA_MODE
# LIVINGAPARTMENTS_MODE
# LIVINGAREA_MODE
# NONLIVINGAPARTMENTS_MODE
# NONLIVINGAREA_MODE
# APARTMENTS_MEDI
# BASEMENTAREA_MEDI
# YEARS_BEGINEXPLUATATION_MEDI
# YEARS_BUILD_MEDI
# COMMONAREA_MEDI
# ELEVATORS_MEDI
# ENTRANCES_MEDI
# FLOORSMAX_MEDI
# FLOORSMIN_MEDI
# LANDAREA_MEDI
# LIVINGAPARTMENTS_MEDI
# LIVINGAREA_MEDI
# NONLIVINGAPARTMENTS_MEDI
# NONLIVINGAREA_MEDI
# TOTALAREA_MODE
# OBS_30_CNT_SOCIAL_CIRCLE
# DEF_30_CNT_SOCIAL_CIRCLE
# OBS_60_CNT_SOCIAL_CIRCLE
# DEF_60_CNT_SOCIAL_CIRCLE
# DAYS_LAST_PHONE_CHANGE
# AMT_REQ_CREDIT_BUREAU_HOUR
# AMT_REQ_CREDIT_BUREAU_DAY
# AMT_REQ_CREDIT_BUREAU_WEEK
# AMT_REQ_CREDIT_BUREAU_MON
# AMT_REQ_CREDIT_BUREAU_QRT
# AMT_REQ_CREDIT_BUREAU_YEAR

In [13]:
# # all numeric columns that were not dropped
# DAYS_BIRTH
# DAYS_ID_PUBLISH
# EXT_SOURCE_1
# DAYS_LAST_PHONE_CHANGE

iteration1df

,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_ID_PUBLISH,...,MAX_OVERDUE_AMOUNT,COUNT_OVERDUE_LOANS,TOTAL_ACTIVE,TOTAL_CLOSED,TOTAL_SOLD,TOTAL_BAD_DEBT,COUNT_LOCAL_CURRENCY_LOANS,COUNT_FOREIGN_CURRENCY_LOANS,RECENT_LOAN_COUNT,TOTAL_ANNUITY
0,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,-11146,-2518,...,0.0,0.0,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0
1,0,Cash loans,N,Family,Pensioner,Secondary / secondary special,Single / not married,Municipal apartment,-21621,-1344,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,4653.0
2,0,Cash loans,N,Unaccompanied,Working,Incomplete higher,Single / not married,With parents,-7907,-586,...,10368.495,1.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0
3,0,Cash loans,Y,Unaccompanied,Commercial associate,Secondary / secondary special,Married,With parents,-10485,-3110,...,21550.5,4.0,3.0,9.0,0.0,0.0,12.0,0.0,0.0,0.0
4,0,Cash loans,N,Unaccompanied,Commercial associate,Higher education,Married,With parents,-10954,-596,...,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20099,0,Cash loans,N,Unaccompanied,Commercial associate,Higher education,Married,With parents,-10592,-2208,...,0.0,0.0,1.0,5.0,0.0,0.0,6.0,0.0,1.0,0.0
20100,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Single / not married,With parents,-8146,-813,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history
20101,0,Cash loans,N,Unaccompanied,State servant,Higher education,Married,Rented apartment,-10567,-2188,...,0.0,0.0,2.0,3.0,0.0,0.0,5.0,0.0,0.0,0.0
20102,0,Cash loans,Y,Unaccompanied,Commercial associate,Secondary / secondary special,Married,Rented apartment,-12847,-35,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history
20103,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,-9327,-1982,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history

In [14]:
# all the numeric columns are not suspiciously correlated to one another, so keep all
cols = [
    'DAYS_BIRTH',
    'DAYS_ID_PUBLISH',
    'EXT_SOURCE_1',
    'DAYS_LAST_PHONE_CHANGE'
]

corr_matrix = iteration1df[cols].corr()

print(corr_matrix)

                        DAYS_BIRTH  DAYS_ID_PUBLISH  EXT_SOURCE_1  \
DAYS_BIRTH                1.000000         0.334369     -0.555735
DAYS_ID_PUBLISH           0.334369         1.000000     -0.182064
EXT_SOURCE_1             -0.555735        -0.182064      1.000000
DAYS_LAST_PHONE_CHANGE    0.187941         0.189101     -0.186784

                        DAYS_LAST_PHONE_CHANGE
DAYS_BIRTH                            0.187941
DAYS_ID_PUBLISH                       0.189101
EXT_SOURCE_1                         -0.186784
DAYS_LAST_PHONE_CHANGE                1.000000

In [17]:
iteration1df

,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_ID_PUBLISH,...,MAX_OVERDUE_AMOUNT,COUNT_OVERDUE_LOANS,TOTAL_ACTIVE,TOTAL_CLOSED,TOTAL_SOLD,TOTAL_BAD_DEBT,COUNT_LOCAL_CURRENCY_LOANS,COUNT_FOREIGN_CURRENCY_LOANS,RECENT_LOAN_COUNT,TOTAL_ANNUITY
0,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,-11146,-2518,...,0.0,0.0,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0
1,0,Cash loans,N,Family,Pensioner,Secondary / secondary special,Single / not married,Municipal apartment,-21621,-1344,...,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,4653.0
2,0,Cash loans,N,Unaccompanied,Working,Incomplete higher,Single / not married,With parents,-7907,-586,...,10368.495,1.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0
3,0,Cash loans,Y,Unaccompanied,Commercial associate,Secondary / secondary special,Married,With parents,-10485,-3110,...,21550.5,4.0,3.0,9.0,0.0,0.0,12.0,0.0,0.0,0.0
4,0,Cash loans,N,Unaccompanied,Commercial associate,Higher education,Married,With parents,-10954,-596,...,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20099,0,Cash loans,N,Unaccompanied,Commercial associate,Higher education,Married,With parents,-10592,-2208,...,0.0,0.0,1.0,5.0,0.0,0.0,6.0,0.0,1.0,0.0
20100,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Single / not married,With parents,-8146,-813,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history
20101,0,Cash loans,N,Unaccompanied,State servant,Higher education,Married,Rented apartment,-10567,-2188,...,0.0,0.0,2.0,3.0,0.0,0.0,5.0,0.0,0.0,0.0
20102,0,Cash loans,Y,Unaccompanied,Commercial associate,Secondary / secondary special,Married,Rented apartment,-12847,-35,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history
20103,0,Cash loans,N,Unaccompanied,Working,Secondary / secondary special,Separated,With parents,-9327,-1982,...,No history,No history,No history,No history,No history,No history,No history,No history,No history,No history

In [34]:
# import numpy as np

# # Replace all "No history" with NaN in the entire DataFrame
# iteration1df = iteration1df.replace("No history", np.nan)

In [ ]:
# sample code

def woe_iv(data):

    working_data = iteration1df.copy() 

    # missing values have been assigned NaN when binning with pd.qcut
    # rename this bin as 'Missing' to consider into WOE calculation
    working_data['Bin_Range'] = working_data['Bin_Range'].astype('object')
    working_data['Bin_Range'] = working_data['Bin_Range'].fillna('Missing')
    
    variable_data = pd.DataFrame()
    variable_data['Bin_Range'] = working_data.groupby(by='Bin_Range', as_index=False).count()['Bin_Range']

    variable_data['Count'] = working_data.groupby(by='Bin_Range', as_index=False).count()['BAD']

    variable_data['Events'] =working_data.groupby(by='Bin_Range', as_index=False).sum()['BAD']

    variable_data['Non_Events'] = variable_data['Count'] - variable_data['Events']

    variable_data['%_of_Events'] = variable_data['Events']/sum(variable_data['Events'])

    variable_data['%_of_Non_Events'] = variable_data['Non_Events']/sum(variable_data['Non_Events'])

    variable_data['WOE'] = np.log(variable_data['%_of_Non_Events'] / variable_data['%_of_Events'])

    variable_data['IV'] = (variable_data['%_of_Non_Events']-variable_data['%_of_Events']) * variable_data['WOE']

    variable_data['total_IV'] = variable_data['IV'].sum()

    return(variable_data)

numeric_cols = iteration1df.select_dtypes(include=['float64', 'int64']).drop('TARGET', axis=1).columns

iv_summary = pd.DataFrame(columns=['Variable', 'IV'])

for col in numeric_cols:
    temp = iteration1df.loc[:, [col, 'TARGET']].copy()
    temp.rename(columns={'TARGET':'BAD'}, inplace=True)
    
    # bin numeric variable into 10 quantiles
    temp['Bin_Range'] = pd.qcut(temp[col], q=10, duplicates='drop')
    
    # calculate WOE and IV
    iv = woe_iv(temp)
    
    # append IV summary
    iv_summary = pd.concat([iv_summary, pd.DataFrame({'Variable':[col], 'IV':[iv['total_IV'].iloc[0]]})], ignore_index=True)

# sort by IV
iv_summary = iv_summary.sort_values(by='IV', ascending=False)
print(iv_summary)

KeyError: 'Bin_Range'